import cv2


InterpolationFlags = {
    "INTER_NEAREST": cv2.INTER_NEAREST,
    "INTER_LINEAR": cv2.INTER_LINEAR,
    "INTER_CUBIC": cv2.INTER_CUBIC,
    "INTER_AREA": cv2.INTER_AREA,
    "INTER_LANCZOS4": cv2.INTER_LANCZOS4,
    "INTER_LINEAR_EXACT": cv2.INTER_LINEAR_EXACT,
    "INTER_NEAREST_EXACT": cv2.INTER_NEAREST_EXACT,
    "INTER_MAX": cv2.INTER_MAX,
    "WARP_FILL_OUTLIERS": cv2.WARP_FILL_OUTLIERS,
    "WARP_INVERSE_MAP": cv2.WARP_INVERSE_MAP
}

InterpolationMasks = {
    "INTER_BITS": cv2.INTER_BITS,
    "INTER_BITS2": cv2.INTER_BITS2,
    "INTER_TAB_SIZE": cv2.INTER_TAB_SIZE,
    "INTER_TAB_SIZE2": cv2.INTER_TAB_SIZE2
}

WarpPolarMode = {
    "WARP_POLAR_LINEAR": cv2.WARP_POLAR_LINEAR,
    "WARP_POLAR_LOG": cv2.WARP_POLAR_LOG
}
