import cv2


AdaptiveThresholdTypes = {
    "ADAPTIVE_THRESH_MEAN_C": cv2.ADAPTIVE_THRESH_MEAN_C,
    "ADAPTIVE_THRESH_GAUSSIAN_C": cv2.ADAPTIVE_THRESH_GAUSSIAN_C
}

DistanceTransformLabelTypes = {
    "DIST_LABEL_CCOMP": cv2.DIST_LABEL_CCOMP,
    "DIST_LABEL_PIXEL": cv2.DIST_LABEL_PIXEL
}

DistanceTransformMasks = {
    "DIST_MASK_3": cv2.DIST_MASK_3,
    "DIST_MASK_5": cv2.DIST_MASK_5,
    "DIST_MASK_PRECISE": cv2.DIST_MASK_PRECISE
}

DistanceTypes = {
    "DIST_USER": cv2.DIST_USER,
    "DIST_L1": cv2.DIST_L1,
    "DIST_L2": cv2.DIST_L2,
    "DIST_C": cv2.DIST_C,
    "DIST_L12": cv2.DIST_L12,
    "DIST_FAIR": cv2.DIST_FAIR,
    "DIST_WELSCH": cv2.DIST_WELSCH,
    "DIST_HUBER": cv2.DIST_HUBER
}

FloodFillFlags = {
    "FLOODFILL_FIXED_RANGE": cv2.FLOODFILL_FIXED_RANGE,
    "FLOODFILL_MASK_ONLY": cv2.FLOODFILL_MASK_ONLY
}

GrabCutClasses = {
    "GC_BGD": cv2.GC_BGD,
    "GC_FGD": cv2.GC_FGD,
    "GC_PR_BGD": cv2.GC_PR_BGD,
    "GC_PR_FGD": cv2.GC_PR_FGD
}

GrabCutModes = {
    "GC_INIT_WITH_RECT": cv2.GC_INIT_WITH_RECT,
    "GC_INIT_WITH_MASK": cv2.GC_INIT_WITH_MASK,
    "GC_EVAL": cv2.GC_EVAL,
    "GC_EVAL_FREEZE_MODEL": cv2.GC_EVAL_FREEZE_MODEL
}

ThresholdTypes = {
    "THRESH_BINARY": cv2.THRESH_BINARY,
    "THRESH_BINARY_INV": cv2.THRESH_BINARY_INV,
    "THRESH_TRUNC": cv2.THRESH_TRUNC,
    "THRESH_TOZERO": cv2.THRESH_TOZERO,
    "THRESH_TOZERO_INV": cv2.THRESH_TOZERO_INV,
    "THRESH_MASK": cv2.THRESH_MASK,
    "THRESH_OTSU": cv2.THRESH_OTSU,
    "THRESH_TRIANGLE": cv2.THRESH_TRIANGLE
}
